### ISSUE TITLE
حذف شماره نسخه از نام برنامه

### ISSUE THREAD

**Issue by xmha97** [abroshan39/ghazal#3]
سلام
فقط درصورتی ورژن برنامه جلوی نام آن ذکر می‌شود که یک محصول جدا به حساب بیاید که در این صورت ورژن‌های مختلف به صورت مستقل از یکدیگر نصب می‌شوند مثلا می‌تواند فوتوشاپ ۲۰۲۳ را همزمان با فوتوشاپ ۲۰۲۲ نصب کرد یا ویژوال استادیو

![image](https://user-images.githubusercontent.com/23485114/210461360-ae4da7a0-2c6c-4274-bca7-02fda1f8a128.png)

اما کروم را درنظر بگیرید، در نامش ورژن ذکر نشده و فقط یک بار میتواند نصب شود.
با توجه به این مورد، لطفا نسخه را از نام شورت کات برنامه و پوشه‌ی آن حذف کنید.

![image](https://user-images.githubusercontent.com/23485114/210461630-99fdbd2a-7337-4d6f-aa20-725da23da8f9.png)

**Comment by abroshan39** [comment]
سلام
ممنون از دقتتون. در نسخهٔ بعدی تصحیح خواهد شد.
تندرست باشید

**Comment by abroshan39** [comment]
سلام
ممنون از شما به خاطر دقتتون. در نسخهٔ بعدی تصحیح خواهد شد.
تندرست باشید

**Comment by abroshan39** [comment]
در [نسخهٔ جدید](https://github.com/abroshan39/ghazal/releases/tag/v1.5) تصحیح شد.

**Comment by abroshan39** [comment]
در [نسخهٔ جدید](https://github.com/abroshan39/ghazal/releases/tag/v1.5) تصحیح شد.

**Comment by xmha97** [comment]
ممنون از شما
