### ISSUE TITLE
پارامتری برای استفاده از اپلیکیشن در حالت پرتابل

### ISSUE THREAD

**Issue by xmha97** [abroshan39/ghazal#4]
سلام
میخواهم برنامه را بر روی فلش بریزم که همه جا بتوانم از آن استفاده کنم
در این حالت معمولا برنامه‌ها پارامتری را درنظر می‌گیرند که با استفاده از ان بتوانیم مسیر دیتای برنامه را مشخص کنیم، مثلا:

1. Google **Chrome** \ Microsoft **Edge** \ Electron Apps:
```
.\chrome.exe --user-data-dir="D:\Data"
```

2. Mozilla **Firefox**:
```
.\firefox.exe -profile="D:\Data"
```

3. **Telegram**:
```
.\telegram.exe -workdir="D:\Data"
```

4. Ankitects **Anki**:
```
.\anki.exe -b="D:\Data"
```

5. LinwoodCloud **Butterfly**:
```
.\butterfly.exe --path="D:\Data"
```

چنین چیزی را برای برنامه می‌خواهم

**Comment by abroshan39** [comment]
سلام
به نکته بسیار خوبی اشاره کردید. در نسخهٔ بعدی با استفاده از فایل ghazal.conf که در کنار فایل اجرایی نرم‌افزار قرار می‌گیرد، این مورد در دسترس خواهد بود. بدین صورت که می‌توان تمام فایل‌های دیتای نرم‌افزار (فایل دیتابیس، فایل تنظیمات و فایل تاریخچه) را به صورت Relative آدرس‌دهی کرد.
موفق و پیروز باشید

**Comment by abroshan39** [comment]
در [نسخهٔ جدید](https://github.com/abroshan39/ghazal/releases/tag/v1.5) این مورد اضافه شد. در قسمت تنظیمات می‌توان مسیر دایرکتوری دیتا را تغییر داد. اگر مسیر انتخاب‌شده، مسیری باشد که فایل اجرائی برنامه در آن قرار دارد یا زیرمجموعه‌ای از آن باشد، این مسیر به‌صورت Relative ذخیره خواهد شد؛ در غیر این صورت این مسیر به‌صورت Absolute ذخیره می‌شود. اما اگر از طریق خط فرمان مسیر دایرکتوری دیتا را تغییر دهید، آدرس به همان شکلی که وارد می‌کنید ذخیره خواهد شد.
محل ذخیره‌سازی آدرس دایرکتوری دیتا در فایل ghazal.conf است که در کنار فایل اجرائی برنامه قرار خواهد گرفت.
```
./ghazal --data-dir="./data"
# OR
./ghazal -d "./data"
```

**Comment by abroshan39** [comment]
در [نسخهٔ جدید](https://github.com/abroshan39/ghazal/releases/tag/v1.5) این مورد اضافه شد. در قسمت تنظیمات می‌توان مسیر دایرکتوری دیتا را تغییر داد. اگر مسیر انتخاب‌شده، مسیری باشد که فایل اجرائی برنامه در آن قرار دارد یا زیرمجموعه‌ای از آن باشد، این مسیر به‌صورت Relative ذخیره خواهد شد؛ در غیر این صورت این مسیر به‌صورت Absolute ذخیره می‌شود. اما اگر از طریق خط فرمان مسیر دایرکتوری دیتا را تغییر دهید، آدرس به همان شکلی که وارد می‌کنید ذخیره خواهد شد.
محل ذخیره‌سازی آدرس دایرکتوری دیتا در فایل ghazal.conf است که در کنار فایل اجرائی برنامه قرار خواهد گرفت.
```
./ghazal --data-dir="./data"
# OR
./ghazal -d "./data"
```

**Comment by xmha97** [comment]
ممنون از شما
حتما تست خواهم کرد و نتیجه را اعلام می‌کنم. 🌹

**Comment by xmha97** [comment]
سلام @abroshan39 
زمانی که برنامه را با پارامتر اجرا می‌کنم، فایل ghazal.conf ساخته می‌شود.
این شاید خوب به نظر برسد اما واقعا خوب نیست.
یه لحظه می‌خوام برنامه رو با یه پروفایل دیگه اجرا کنم، مسیر پیش‌فرض دیتاش تغییر میکنه.
همچنین می‌خواهم نسخه‌ی PortableApps.com برنامه رو ایجاد کنم
قانون اینه که فولدر برنامه تغییر نکنه و وجود این فایل این قانون رو نقض میکنه
لطفا این ویژگی رو حذف کنید، با تشکر

**Comment by abroshan39** [comment]
سلام
پرتابل‌سازی به گونه‌ای انجام شده که نیاز اکثر کاربرها رو برآورده می‌کنه. اطلاع دقیقی از سایت PortableApps.com ندارم. آیا برای سیستم‌عامل‌های شبه‌یونیکس هم میتونه پرتابل‌سازی رو انجام بده؟
اما در کل اولویت من برای توسعه نرم‌افزار غزل دسترسی هر چه دقیق‌تر به اطلاعات موجود در پایگاه داده، و در واقع «دقیق‌تر کردن جست‌وجو» است. متاسفانه به دلیل مشغله کاری فرصت زیادی برای توسعه نرم‌افزار به وجود نمیاد.
میتونید با تغییر در سورس کد ویژگی مد نظر خودتون رو اضافه کنید و به راحتی اون رو کامپایل کنید.
سالم باشید

**Comment by xmha97** [comment]
اوکی، ممنون از شما آقای دکتر 🌹
