### ISSUE TITLE
64-bit version

### ISSUE THREAD

**Issue by xmha97** [abroshan39/ghazal#7]
سلام، چرا در ویندوز فقط نسخه‌ی ۳۲-بیتی ارائه میشه؟
با توجه به این که ویندوز (هم مثل لینوکس) به ادامه‌ی انتشار سیستم عامل ۳۲-بیتی ادامه نمیدهد، لطفا نسخه‌ی ۶۴-بیتی هم منتشر کنید.
با تشکر.

**Comment by abroshan39** [comment]
سلام
پشتیبانی از اپلیکیشن‌های 32 بیتی در ویندوز هنوز متوقف نشده و فعلا نیازی به ساخت نسخه 64 بیتی نیست.
سالم باشید

**Comment by xmha97** [comment]
سیستم عامل ویندوز فقط به صورت ۶۴-بیتی منتشر میشه اما همچنان میشه از نرم‌افزارهای ۳۲-بیتی هم استفاده کرد، پس بله فعلا مهم نیست.
